language: rust

env:
  global:
    - RUST_BACKTRACE=1

matrix:
  fast_finish: true
  allow_failures:
    - rust: beta
    - rust: nightly

  include:
    - env: TARGET=x86_64-unknown-linux-musl
    - env: TARGET=x86_64-apple-darwin
      os: osx

    # Testing other channels
    - env: TARGET=x86_64-unknown-linux-musl
      rust: beta
    - env: TARGET=x86_64-unknown-linux-musl
      rust: nightly

install:
  - rustup target add "$TARGET"

script:
  - cargo test --target "$TARGET" --release --locked
  - cargo run --target "$TARGET" --release --locked help

  # Package for the release
  - |
    ./ci/package.py \
      --rust-target "$TARGET" \
      --dest-dir dist/release

deploy:
  api_key:
    secure: "oogEfvEBMZapU13+j9iSUxJ2QFyhqhqdTcJTIXQXGkUE9gmvZ7+jMe2LtL9cM1cJ4RwEL3ku6De8xPbmGh7O7wQ/X3WNM1rNsxe1zl4Q/zwfCERs8IV3x/BZuDEeuQETtZKprvf0i+ZKnoGT/6UO699fRNnvaP0ZdNVzhKiT53rZ14PuvhdeviM0U2eoxJmbKEyL2EOcdqTmW6rkGgiUwAJMMi4+AurQq+eTISPibXah6QJ37BVcvmGxh4Q/55+iQUOEOub7xjYyhZRGF8USOOf6TODqp+WFCKIsrogGs9kh1rqpLCRC+2SRnZW1T36Lqhp3Fkgc0+Wy4H+dPl3Us+0zRI/ej2jVKDd9Ln94N4qkAH/RgRMxucZ3Syvy8C7BvXnEalC6JmI08tTm1ckuazyM1TN3y+ssbsmMeH3GLVrajmRZ199UAKNr0td/Iq8Ql9hNmuYGxAqR0DLFJMSUnK5tYDMuKrp689QHIk5A9HhFtNgyjZOa/uYctmSBDCTpJ64TqqZ4Z7ZXH4hMs7n5daSkBEGtlu9B96CjY0w5n98JQLPWxodtzjDkIwiTshPGX1kw0b2UE/+Mu3Ujz1YUbuL+c0O8+yr6Iw8Bj85Yb/dC541rjhn4haZsVXVJM/uHtEJ9YLLN/rD3n48Omx0H4EJ35BvLKJhW6/XLIZ83/vI="
  file_glob: true
  file: "dist/release/*"
  on:
    condition: $TRAVIS_RUST_VERSION = stable
    tags: true
  provider: releases
  skip_cleanup: true

# Cache ~/.cargo without ~/.cargo/registry. Also don't cache ./target
# See: https://levans.fr/rust_travis_cache.html
cache:
  directories:
    - /home/travis/.cargo
before_cache:
  - rm -rf /home/travis/.cargo/registry

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

notifications:
  email:
    on_success: never
