[package]
name = "alt"
version = "1.0.4"
description = "A tool for switching between different version so commands based on the current directory."
authors = ["Boris Bera <bera.boris@gmail.com>"]
edition = "2018"
license = "MIT"
readme = "README.md"

build = "build.rs"
publish = false

[dependencies]
clap = "2.33.0"
toml = "0.5.3"
console = "0.8.0"
regex = "1"
lazy_static = "1.3.0"
dialoguer = "0.4.0"
glob = "0.3.0"

[dev-dependencies]
assert_cmd = "0.11"
escargot = "0.5"
rand = "0.7"

[build-dependencies]
clap = "2.33.0"

[profile.release]
lto = true
