[package]
name = "alt"
version = "1.0.5"
description = "A tool for switching between different version so commands based on the current directory."
authors = ["Boris Bera <bera.boris@gmail.com>"]
edition = "2018"
license = "MIT"
readme = "README.md"

build = "build.rs"
publish = false

[package.metadata.deb]
assets = [
    ["target/release/alt", "usr/bin/alt", "755"],
    ["README.md", "usr/share/doc/alt/README.md", "644"],
    ["etc/profile.d/alt.sh", "etc/profile.d/alt.sh", "644"],
    ["etc/fish/conf.d/alt.fish", "etc/fish/conf.d/alt.fish", "644"]
]

[profile.release]
lto = true

[dependencies]
clap = "2.33.0"
toml = "0.5.3"
console = "0.8.0"
regex = "1"
lazy_static = "1.4.0"
dialoguer = "0.4.0"
glob = "0.3.0"

[dev-dependencies]
assert_cmd = "0.11"
escargot = "0.5"
rand = "0.7"

[build-dependencies]
clap = "2.33.0"
