[package]
name = "alt"
version = "1.0.1"
authors = ["Boris Bera <bera.boris@gmail.com>"]

[dependencies]
clap = "2.32.0"
toml = "0.4.6"
console = "0.6.1"
regex = "1"
lazy_static = "1.0.2"
dialoguer = "0.1.0"
glob = "0.2.11"

[dev-dependencies]
assert_cmd = "0.6.0"
rand = "0.5"
