[package]
name = "alt"
version = "0.2.0"
authors = ["Boris Bera <bera.boris@gmail.com>"]

[dependencies]
clap = "2.32.0"
toml = "0.4.6"
console = "0.6.1"
regex = "1"
lazy_static = "1.0.2"
dialoguer = "0.1.0"
