name: CI

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  check:
    name: cargo check

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - uses: actions-rs/cargo@v1
        with:
          command: check

  fmt-check:
    name: cargo fmt --check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
      - name: print rustfmt version
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --version
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check --color=always

  test-rust:
    name: cargo test

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo build
      - run: cargo test

  package:
    uses: ./.github/workflows/package.yml

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - name: print clippy version
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --version
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features -- -D warnings

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ludeeus/action-shellcheck@2.0.0
        with:
          check_together: 'yes'

  fish-check:
    name: check fish code

    strategy:
      matrix:
        include:
          - ppa: ppa:fish-shell/release-3
            os: ubuntu-latest
          - ppa: ppa:fish-shell/release-2
            # fish 2 ppa doesn't support ubuntu 20.04
            os: ubuntu-18.04
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y software-properties-common
          sudo apt-add-repository -y ${{ matrix.ppa }}
          sudo apt-get update -y
          sudo apt-get install fish
      - name: Fish syntax check
        run: find . -iname '*.fish' -print0 | xargs -n1 -0t fish -n

  python-flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install flake8
      - run: flake8 .

  python-black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install black
      - run: black --check .
