name: Release a new version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number to release (ex: 1.2.3)'
        required: true

jobs:
  prepare-release:
    name: Prepare release

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Configure git user.*
        run: |
          git config user.name 'Github Actions'
          git config user.email noreply@github.com

      # Update Changelog
      - name: Update changelog
        uses: thomaseizinger/keep-a-changelog-new-release@v1
        with:
          version: v${{ github.event.inputs.version }}

      # Bump version in Cargo.toml & Cargo.lock
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install toml-cli
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: toml-cli
      - name: Bump version in Cargo.toml
        run: |
          toml set Cargo.toml \
            package.version '${{ github.event.inputs.version }}' \
            > Cargo.toml.new
          rm Cargo.toml
          mv Cargo.toml.new Cargo.toml
      - name: Update Cargo.lock (using cargo build)
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: Show changes about to be committed
        run: git diff --color
